apiVersion: v1
kind: Service
metadata:
  name: concourse-external
  labels:
    name: concourse-external
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    app: web
    tier: frontend
