apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: backend
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:9.5
        env:
        - name: POSTGRES_DB
          value: concourse
        - name: POSTGRES_USER
          value: concourse
        - name: POSTGRES_PASSWORD
          value: concourse
        - name: PGDATA
          value: /persist/database
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /persist
