apiVersion: v1
kind: Service
metadata:
  name: concourse-external
  labels:
    name: concourse-external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::375783000519:server-certificate/sding-certificate
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    app: web
    tier: frontend
